# Generated by Django 3.2.5 on 2021-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is it deleted')),
                ('creat_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creat timestamp')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='modify timestamp')),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete timestamp')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
