# Generated by Django 3.2.5 on 2021-12-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20211231_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Write your message here', verbose_name='Message'),
        ),
    ]
