# Generated by Django 3.2.5 on 2021-08-17 07:36

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[customer.models.phone_validator], verbose_name='Phone'),
        ),
    ]
