# Generated by Django 3.2.5 on 2021-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(blank=True, default=None, help_text='Detail of the address, like alley name or house number', max_length=100, null=True, verbose_name='Detail'),
        ),
    ]
