# Generated by Django 3.2.5 on 2021-08-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is it deleted')),
                ('creat_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creat timestamp')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='modify timestamp')),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='timestampmixin_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmixin'),
            preserve_default=False,
        ),
    ]
