# Generated by Django 3.2.5 on 2021-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Name of the discount', max_length=50, null=True, verbose_name='Name'),
        ),
    ]
