# Generated by Django 3.2.5 on 2021-08-07 07:55

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Input positive amount in Toomaan/1000', validators=[product.models.positive_number], verbose_name='Price'),
        ),
    ]
