# Generated by Django 3.2.5 on 2021-08-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is it deleted')),
                ('creat_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creat timestamp')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='modify timestamp')),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete timestamp')),
                ('payment_type', models.CharField(choices=[('O', 'Online'), ('C', 'Card (In-person payment)')], default='O', max_length=1, verbose_name='Payment Type')),
                ('status', models.CharField(choices=[('Cn', 'Canceled'), ('Ps', 'Posting'), ('Pr', 'Processing')], default='Pr', help_text='Types of the status', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['creat_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is it deleted')),
                ('creat_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creat timestamp')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='modify timestamp')),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete timestamp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['creat_timestamp'],
            },
        ),
    ]
