# Generated by Django 3.2.5 on 2021-08-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='order.order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
